import { ChampionMastery } from './Entity/ChampionMastery';

export const CHAMPMOCK: ChampionMastery[] = [
    {
        "championId": 114,
        "championLevel": 7,
        "championPoints": 162446,
        "lastPlayTime": 1631389510000,
        "championPointsSinceLastLevel": 140846,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 81,
        "championLevel": 7,
        "championPoints": 145437,
        "lastPlayTime": 1631129896000,
        "championPointsSinceLastLevel": 123837,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 412,
        "championLevel": 7,
        "championPoints": 120679,
        "lastPlayTime": 1631402253000,
        "championPointsSinceLastLevel": 99079,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 67,
        "championLevel": 7,
        "championPoints": 96673,
        "lastPlayTime": 1630955340000,
        "championPointsSinceLastLevel": 75073,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 45,
        "championLevel": 7,
        "championPoints": 75074,
        "lastPlayTime": 1630261082000,
        "championPointsSinceLastLevel": 53474,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 202,
        "championLevel": 7,
        "championPoints": 74114,
        "lastPlayTime": 1629583891000,
        "championPointsSinceLastLevel": 52514,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 555,
        "championLevel": 7,
        "championPoints": 72163,
        "lastPlayTime": 1631453696000,
        "championPointsSinceLastLevel": 50563,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 13,
        "championLevel": 7,
        "championPoints": 68320,
        "lastPlayTime": 1631993551000,
        "championPointsSinceLastLevel": 46720,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 64,
        "championLevel": 7,
        "championPoints": 66897,
        "lastPlayTime": 1629138124000,
        "championPointsSinceLastLevel": 45297,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 498,
        "championLevel": 7,
        "championPoints": 66601,
        "lastPlayTime": 1628716262000,
        "championPointsSinceLastLevel": 45001,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 51,
        "championLevel": 7,
        "championPoints": 63459,
        "lastPlayTime": 1631310669000,
        "championPointsSinceLastLevel": 41859,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 38,
        "championLevel": 7,
        "championPoints": 62750,
        "lastPlayTime": 1630107571000,
        "championPointsSinceLastLevel": 41150,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 86,
        "championLevel": 7,
        "championPoints": 60306,
        "lastPlayTime": 1618709103000,
        "championPointsSinceLastLevel": 38706,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 18,
        "championLevel": 7,
        "championPoints": 59137,
        "lastPlayTime": 1630520944000,
        "championPointsSinceLastLevel": 37537,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 145,
        "championLevel": 7,
        "championPoints": 56314,
        "lastPlayTime": 1625777006000,
        "championPointsSinceLastLevel": 34714,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 157,
        "championLevel": 6,
        "championPoints": 52991,
        "lastPlayTime": 1626217870000,
        "championPointsSinceLastLevel": 31391,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 2,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 22,
        "championLevel": 6,
        "championPoints": 50161,
        "lastPlayTime": 1631301375000,
        "championPointsSinceLastLevel": 28561,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 2,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 222,
        "championLevel": 7,
        "championPoints": 49759,
        "lastPlayTime": 1630354098000,
        "championPointsSinceLastLevel": 28159,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 48,
        "championLevel": 7,
        "championPoints": 49010,
        "lastPlayTime": 1614384295000,
        "championPointsSinceLastLevel": 27410,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 24,
        "championLevel": 7,
        "championPoints": 48682,
        "lastPlayTime": 1628292613000,
        "championPointsSinceLastLevel": 27082,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 39,
        "championLevel": 6,
        "championPoints": 48594,
        "lastPlayTime": 1631996477000,
        "championPointsSinceLastLevel": 26994,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 1,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 99,
        "championLevel": 6,
        "championPoints": 46806,
        "lastPlayTime": 1619038501000,
        "championPointsSinceLastLevel": 25206,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 4,
        "championLevel": 6,
        "championPoints": 44264,
        "lastPlayTime": 1631559277000,
        "championPointsSinceLastLevel": 22664,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 1,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 236,
        "championLevel": 6,
        "championPoints": 39131,
        "lastPlayTime": 1630072957000,
        "championPointsSinceLastLevel": 17531,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 2,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 92,
        "championLevel": 6,
        "championPoints": 38915,
        "lastPlayTime": 1627068624000,
        "championPointsSinceLastLevel": 17315,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 40,
        "championLevel": 7,
        "championPoints": 38446,
        "lastPlayTime": 1630011638000,
        "championPointsSinceLastLevel": 16846,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 8,
        "championLevel": 5,
        "championPoints": 36682,
        "lastPlayTime": 1621639173000,
        "championPointsSinceLastLevel": 15082,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 84,
        "championLevel": 7,
        "championPoints": 36461,
        "lastPlayTime": 1631648869000,
        "championPointsSinceLastLevel": 14861,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 10,
        "championLevel": 7,
        "championPoints": 35994,
        "lastPlayTime": 1629051667000,
        "championPointsSinceLastLevel": 14394,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 238,
        "championLevel": 6,
        "championPoints": 34807,
        "lastPlayTime": 1628710494000,
        "championPointsSinceLastLevel": 13207,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 7,
        "championLevel": 5,
        "championPoints": 32146,
        "lastPlayTime": 1629319726000,
        "championPointsSinceLastLevel": 10546,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 1,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 15,
        "championLevel": 5,
        "championPoints": 31912,
        "lastPlayTime": 1630013313000,
        "championPointsSinceLastLevel": 10312,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 122,
        "championLevel": 5,
        "championPoints": 31372,
        "lastPlayTime": 1630704736000,
        "championPointsSinceLastLevel": 9772,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 1,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 203,
        "championLevel": 6,
        "championPoints": 30230,
        "lastPlayTime": 1632007989000,
        "championPointsSinceLastLevel": 8630,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 61,
        "championLevel": 6,
        "championPoints": 30053,
        "lastPlayTime": 1630112798000,
        "championPointsSinceLastLevel": 8453,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 245,
        "championLevel": 6,
        "championPoints": 29540,
        "lastPlayTime": 1628629101000,
        "championPointsSinceLastLevel": 7940,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 28,
        "championLevel": 6,
        "championPoints": 29468,
        "lastPlayTime": 1631042015000,
        "championPointsSinceLastLevel": 7868,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 107,
        "championLevel": 5,
        "championPoints": 29351,
        "lastPlayTime": 1631652471000,
        "championPointsSinceLastLevel": 7751,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 14,
        "championLevel": 5,
        "championPoints": 28724,
        "lastPlayTime": 1628452106000,
        "championPointsSinceLastLevel": 7124,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 421,
        "championLevel": 5,
        "championPoints": 28555,
        "lastPlayTime": 1614463544000,
        "championPointsSinceLastLevel": 6955,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 105,
        "championLevel": 5,
        "championPoints": 28137,
        "lastPlayTime": 1614528241000,
        "championPointsSinceLastLevel": 6537,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 78,
        "championLevel": 5,
        "championPoints": 28133,
        "lastPlayTime": 1630106109000,
        "championPointsSinceLastLevel": 6533,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 41,
        "championLevel": 5,
        "championPoints": 27757,
        "lastPlayTime": 1630178157000,
        "championPointsSinceLastLevel": 6157,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 142,
        "championLevel": 5,
        "championPoints": 27234,
        "lastPlayTime": 1630101758000,
        "championPointsSinceLastLevel": 5634,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 112,
        "championLevel": 5,
        "championPoints": 27025,
        "lastPlayTime": 1631998678000,
        "championPointsSinceLastLevel": 5425,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 1,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 104,
        "championLevel": 5,
        "championPoints": 26545,
        "lastPlayTime": 1605218437000,
        "championPointsSinceLastLevel": 4945,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 517,
        "championLevel": 6,
        "championPoints": 26121,
        "lastPlayTime": 1631650936000,
        "championPointsSinceLastLevel": 4521,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 1,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 121,
        "championLevel": 5,
        "championPoints": 25606,
        "lastPlayTime": 1623005006000,
        "championPointsSinceLastLevel": 4006,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 54,
        "championLevel": 5,
        "championPoints": 25364,
        "lastPlayTime": 1630498702000,
        "championPointsSinceLastLevel": 3764,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 235,
        "championLevel": 5,
        "championPoints": 22947,
        "lastPlayTime": 1628895515000,
        "championPointsSinceLastLevel": 1347,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 17,
        "championLevel": 5,
        "championPoints": 22538,
        "lastPlayTime": 1613265472000,
        "championPointsSinceLastLevel": 938,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 43,
        "championLevel": 5,
        "championPoints": 22458,
        "lastPlayTime": 1630539782000,
        "championPointsSinceLastLevel": 858,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 53,
        "championLevel": 5,
        "championPoints": 22444,
        "lastPlayTime": 1631038411000,
        "championPointsSinceLastLevel": 844,
        "championPointsUntilNextLevel": 0,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 75,
        "championLevel": 5,
        "championPoints": 22312,
        "lastPlayTime": 1619033645000,
        "championPointsSinceLastLevel": 712,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 89,
        "championLevel": 5,
        "championPoints": 22072,
        "lastPlayTime": 1632009253000,
        "championPointsSinceLastLevel": 472,
        "championPointsUntilNextLevel": 0,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 134,
        "championLevel": 4,
        "championPoints": 21480,
        "lastPlayTime": 1631047506000,
        "championPointsSinceLastLevel": 8880,
        "championPointsUntilNextLevel": 120,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 35,
        "championLevel": 4,
        "championPoints": 21255,
        "lastPlayTime": 1631322408000,
        "championPointsSinceLastLevel": 8655,
        "championPointsUntilNextLevel": 345,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 429,
        "championLevel": 4,
        "championPoints": 20458,
        "lastPlayTime": 1630451060000,
        "championPointsSinceLastLevel": 7858,
        "championPointsUntilNextLevel": 1142,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 80,
        "championLevel": 4,
        "championPoints": 19353,
        "lastPlayTime": 1631054957000,
        "championPointsSinceLastLevel": 6753,
        "championPointsUntilNextLevel": 2247,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 120,
        "championLevel": 4,
        "championPoints": 19319,
        "lastPlayTime": 1618605934000,
        "championPointsSinceLastLevel": 6719,
        "championPointsUntilNextLevel": 2281,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 115,
        "championLevel": 4,
        "championPoints": 18320,
        "lastPlayTime": 1618788221000,
        "championPointsSinceLastLevel": 5720,
        "championPointsUntilNextLevel": 3280,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 96,
        "championLevel": 4,
        "championPoints": 17929,
        "lastPlayTime": 1630791313000,
        "championPointsSinceLastLevel": 5329,
        "championPointsUntilNextLevel": 3671,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 110,
        "championLevel": 4,
        "championPoints": 17694,
        "lastPlayTime": 1631298947000,
        "championPointsSinceLastLevel": 5094,
        "championPointsUntilNextLevel": 3906,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 82,
        "championLevel": 4,
        "championPoints": 17456,
        "lastPlayTime": 1632003013000,
        "championPointsSinceLastLevel": 4856,
        "championPointsUntilNextLevel": 4144,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 147,
        "championLevel": 4,
        "championPoints": 17156,
        "lastPlayTime": 1631405414000,
        "championPointsSinceLastLevel": 4556,
        "championPointsUntilNextLevel": 4444,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 27,
        "championLevel": 4,
        "championPoints": 16814,
        "lastPlayTime": 1626913061000,
        "championPointsSinceLastLevel": 4214,
        "championPointsUntilNextLevel": 4786,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 266,
        "championLevel": 4,
        "championPoints": 16714,
        "lastPlayTime": 1631035998000,
        "championPointsSinceLastLevel": 4114,
        "championPointsUntilNextLevel": 4886,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 57,
        "championLevel": 4,
        "championPoints": 15861,
        "lastPlayTime": 1630181105000,
        "championPointsSinceLastLevel": 3261,
        "championPointsUntilNextLevel": 5739,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 103,
        "championLevel": 4,
        "championPoints": 15621,
        "lastPlayTime": 1631718582000,
        "championPointsSinceLastLevel": 3021,
        "championPointsUntilNextLevel": 5979,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 11,
        "championLevel": 4,
        "championPoints": 14764,
        "lastPlayTime": 1632001211000,
        "championPointsSinceLastLevel": 2164,
        "championPointsUntilNextLevel": 6836,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 141,
        "championLevel": 4,
        "championPoints": 14750,
        "lastPlayTime": 1628539392000,
        "championPointsSinceLastLevel": 2150,
        "championPointsUntilNextLevel": 6850,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 79,
        "championLevel": 4,
        "championPoints": 14624,
        "lastPlayTime": 1630500129000,
        "championPointsSinceLastLevel": 2024,
        "championPointsUntilNextLevel": 6976,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 154,
        "championLevel": 4,
        "championPoints": 14317,
        "lastPlayTime": 1632012419000,
        "championPointsSinceLastLevel": 1717,
        "championPointsUntilNextLevel": 7283,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 60,
        "championLevel": 4,
        "championPoints": 13531,
        "lastPlayTime": 1606665632000,
        "championPointsSinceLastLevel": 931,
        "championPointsUntilNextLevel": 8069,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 37,
        "championLevel": 4,
        "championPoints": 13061,
        "lastPlayTime": 1628711209000,
        "championPointsSinceLastLevel": 461,
        "championPointsUntilNextLevel": 8539,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 21,
        "championLevel": 4,
        "championPoints": 12667,
        "lastPlayTime": 1621725910000,
        "championPointsSinceLastLevel": 67,
        "championPointsUntilNextLevel": 8933,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 42,
        "championLevel": 4,
        "championPoints": 12609,
        "lastPlayTime": 1631971923000,
        "championPointsSinceLastLevel": 9,
        "championPointsUntilNextLevel": 8991,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 55,
        "championLevel": 3,
        "championPoints": 12480,
        "lastPlayTime": 1631320959000,
        "championPointsSinceLastLevel": 6480,
        "championPointsUntilNextLevel": 120,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 69,
        "championLevel": 3,
        "championPoints": 12084,
        "lastPlayTime": 1632006208000,
        "championPointsSinceLastLevel": 6084,
        "championPointsUntilNextLevel": 516,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 62,
        "championLevel": 3,
        "championPoints": 11920,
        "lastPlayTime": 1630179267000,
        "championPointsSinceLastLevel": 5920,
        "championPointsUntilNextLevel": 680,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 31,
        "championLevel": 3,
        "championPoints": 11583,
        "lastPlayTime": 1630272722000,
        "championPointsSinceLastLevel": 5583,
        "championPointsUntilNextLevel": 1017,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 516,
        "championLevel": 3,
        "championPoints": 11223,
        "lastPlayTime": 1632010693000,
        "championPointsSinceLastLevel": 5223,
        "championPointsUntilNextLevel": 1377,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 59,
        "championLevel": 3,
        "championPoints": 11043,
        "lastPlayTime": 1632013739000,
        "championPointsSinceLastLevel": 5043,
        "championPointsUntilNextLevel": 1557,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 29,
        "championLevel": 3,
        "championPoints": 11020,
        "lastPlayTime": 1630075190000,
        "championPointsSinceLastLevel": 5020,
        "championPointsUntilNextLevel": 1580,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 101,
        "championLevel": 3,
        "championPoints": 10777,
        "lastPlayTime": 1630960585000,
        "championPointsSinceLastLevel": 4777,
        "championPointsUntilNextLevel": 1823,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 12,
        "championLevel": 3,
        "championPoints": 10662,
        "lastPlayTime": 1631219062000,
        "championPointsSinceLastLevel": 4662,
        "championPointsUntilNextLevel": 1938,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 76,
        "championLevel": 3,
        "championPoints": 10233,
        "lastPlayTime": 1614198166000,
        "championPointsSinceLastLevel": 4233,
        "championPointsUntilNextLevel": 2367,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 30,
        "championLevel": 3,
        "championPoints": 10139,
        "lastPlayTime": 1619910771000,
        "championPointsSinceLastLevel": 4139,
        "championPointsUntilNextLevel": 2461,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 201,
        "championLevel": 3,
        "championPoints": 10057,
        "lastPlayTime": 1631455568000,
        "championPointsSinceLastLevel": 4057,
        "championPointsUntilNextLevel": 2543,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 34,
        "championLevel": 3,
        "championPoints": 9719,
        "lastPlayTime": 1614024592000,
        "championPointsSinceLastLevel": 3719,
        "championPointsUntilNextLevel": 2881,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 26,
        "championLevel": 3,
        "championPoints": 9679,
        "lastPlayTime": 1630709585000,
        "championPointsSinceLastLevel": 3679,
        "championPointsUntilNextLevel": 2921,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 875,
        "championLevel": 3,
        "championPoints": 9578,
        "lastPlayTime": 1631410051000,
        "championPointsSinceLastLevel": 3578,
        "championPointsUntilNextLevel": 3022,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 1,
        "championLevel": 3,
        "championPoints": 9474,
        "lastPlayTime": 1626807148000,
        "championPointsSinceLastLevel": 3474,
        "championPointsUntilNextLevel": 3126,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 497,
        "championLevel": 3,
        "championPoints": 9424,
        "lastPlayTime": 1631974163000,
        "championPointsSinceLastLevel": 3424,
        "championPointsUntilNextLevel": 3176,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 98,
        "championLevel": 3,
        "championPoints": 9411,
        "lastPlayTime": 1630111753000,
        "championPointsSinceLastLevel": 3411,
        "championPointsUntilNextLevel": 3189,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 246,
        "championLevel": 3,
        "championPoints": 8997,
        "lastPlayTime": 1630104456000,
        "championPointsSinceLastLevel": 2997,
        "championPointsUntilNextLevel": 3603,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 77,
        "championLevel": 3,
        "championPoints": 8821,
        "lastPlayTime": 1626117750000,
        "championPointsSinceLastLevel": 2821,
        "championPointsUntilNextLevel": 3779,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 127,
        "championLevel": 3,
        "championPoints": 8810,
        "lastPlayTime": 1592681855000,
        "championPointsSinceLastLevel": 2810,
        "championPointsUntilNextLevel": 3790,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 119,
        "championLevel": 3,
        "championPoints": 8762,
        "lastPlayTime": 1619914018000,
        "championPointsSinceLastLevel": 2762,
        "championPointsUntilNextLevel": 3838,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 117,
        "championLevel": 3,
        "championPoints": 8512,
        "lastPlayTime": 1630497443000,
        "championPointsSinceLastLevel": 2512,
        "championPointsUntilNextLevel": 4088,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 523,
        "championLevel": 3,
        "championPoints": 8214,
        "lastPlayTime": 1629142721000,
        "championPointsSinceLastLevel": 2214,
        "championPointsUntilNextLevel": 4386,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 432,
        "championLevel": 3,
        "championPoints": 8103,
        "lastPlayTime": 1615146407000,
        "championPointsSinceLastLevel": 2103,
        "championPointsUntilNextLevel": 4497,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 131,
        "championLevel": 3,
        "championPoints": 7983,
        "lastPlayTime": 1630594523000,
        "championPointsSinceLastLevel": 1983,
        "championPointsUntilNextLevel": 4617,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 223,
        "championLevel": 3,
        "championPoints": 7831,
        "lastPlayTime": 1631050042000,
        "championPointsSinceLastLevel": 1831,
        "championPointsUntilNextLevel": 4769,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 3,
        "championLevel": 3,
        "championPoints": 7672,
        "lastPlayTime": 1631046082000,
        "championPointsSinceLastLevel": 1672,
        "championPointsUntilNextLevel": 4928,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 72,
        "championLevel": 3,
        "championPoints": 7568,
        "lastPlayTime": 1622335268000,
        "championPointsSinceLastLevel": 1568,
        "championPointsUntilNextLevel": 5032,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 161,
        "championLevel": 3,
        "championPoints": 7544,
        "lastPlayTime": 1623538623000,
        "championPointsSinceLastLevel": 1544,
        "championPointsUntilNextLevel": 5056,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 360,
        "championLevel": 3,
        "championPoints": 7500,
        "lastPlayTime": 1630788893000,
        "championPointsSinceLastLevel": 1500,
        "championPointsUntilNextLevel": 5100,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 58,
        "championLevel": 3,
        "championPoints": 7499,
        "lastPlayTime": 1626563120000,
        "championPointsSinceLastLevel": 1499,
        "championPointsUntilNextLevel": 5101,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 111,
        "championLevel": 3,
        "championPoints": 7190,
        "lastPlayTime": 1623182946000,
        "championPointsSinceLastLevel": 1190,
        "championPointsUntilNextLevel": 5410,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 36,
        "championLevel": 3,
        "championPoints": 6994,
        "lastPlayTime": 1630109154000,
        "championPointsSinceLastLevel": 994,
        "championPointsUntilNextLevel": 5606,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 68,
        "championLevel": 3,
        "championPoints": 6799,
        "lastPlayTime": 1631107352000,
        "championPointsSinceLastLevel": 799,
        "championPointsUntilNextLevel": 5801,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 133,
        "championLevel": 3,
        "championPoints": 6710,
        "lastPlayTime": 1620523631000,
        "championPointsSinceLastLevel": 710,
        "championPointsUntilNextLevel": 5890,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 19,
        "championLevel": 3,
        "championPoints": 6703,
        "lastPlayTime": 1613938832000,
        "championPointsSinceLastLevel": 703,
        "championPointsUntilNextLevel": 5897,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 32,
        "championLevel": 3,
        "championPoints": 6660,
        "lastPlayTime": 1630544358000,
        "championPointsSinceLastLevel": 660,
        "championPointsUntilNextLevel": 5940,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 2,
        "championLevel": 3,
        "championPoints": 6566,
        "lastPlayTime": 1625865362000,
        "championPointsSinceLastLevel": 566,
        "championPointsUntilNextLevel": 6034,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 33,
        "championLevel": 3,
        "championPoints": 6484,
        "lastPlayTime": 1619550884000,
        "championPointsSinceLastLevel": 484,
        "championPointsUntilNextLevel": 6116,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 163,
        "championLevel": 3,
        "championPoints": 6410,
        "lastPlayTime": 1608674394000,
        "championPointsSinceLastLevel": 410,
        "championPointsUntilNextLevel": 6190,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 74,
        "championLevel": 3,
        "championPoints": 6303,
        "lastPlayTime": 1618519519000,
        "championPointsSinceLastLevel": 303,
        "championPointsUntilNextLevel": 6297,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 267,
        "championLevel": 3,
        "championPoints": 6277,
        "lastPlayTime": 1631658580000,
        "championPointsSinceLastLevel": 277,
        "championPointsUntilNextLevel": 6323,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 102,
        "championLevel": 2,
        "championPoints": 5860,
        "lastPlayTime": 1614630941000,
        "championPointsSinceLastLevel": 4060,
        "championPointsUntilNextLevel": 140,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 350,
        "championLevel": 2,
        "championPoints": 5819,
        "lastPlayTime": 1626641791000,
        "championPointsSinceLastLevel": 4019,
        "championPointsUntilNextLevel": 181,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 5,
        "championLevel": 2,
        "championPoints": 5763,
        "lastPlayTime": 1631912210000,
        "championPointsSinceLastLevel": 3963,
        "championPointsUntilNextLevel": 237,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 234,
        "championLevel": 2,
        "championPoints": 5697,
        "lastPlayTime": 1630445437000,
        "championPointsSinceLastLevel": 3897,
        "championPointsUntilNextLevel": 303,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 16,
        "championLevel": 2,
        "championPoints": 5423,
        "lastPlayTime": 1630792648000,
        "championPointsSinceLastLevel": 3623,
        "championPointsUntilNextLevel": 577,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 150,
        "championLevel": 2,
        "championPoints": 5163,
        "lastPlayTime": 1631138695000,
        "championPointsSinceLastLevel": 3363,
        "championPointsUntilNextLevel": 837,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 9,
        "championLevel": 2,
        "championPoints": 5087,
        "lastPlayTime": 1630959324000,
        "championPointsSinceLastLevel": 3287,
        "championPointsUntilNextLevel": 913,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 85,
        "championLevel": 2,
        "championPoints": 4732,
        "lastPlayTime": 1630542959000,
        "championPointsSinceLastLevel": 2932,
        "championPointsUntilNextLevel": 1268,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 887,
        "championLevel": 2,
        "championPoints": 4474,
        "lastPlayTime": 1631392896000,
        "championPointsSinceLastLevel": 2674,
        "championPointsUntilNextLevel": 1526,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 268,
        "championLevel": 2,
        "championPoints": 3973,
        "lastPlayTime": 1630599327000,
        "championPointsSinceLastLevel": 2173,
        "championPointsUntilNextLevel": 2027,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 23,
        "championLevel": 2,
        "championPoints": 3950,
        "lastPlayTime": 1614970662000,
        "championPointsSinceLastLevel": 2150,
        "championPointsUntilNextLevel": 2050,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 136,
        "championLevel": 2,
        "championPoints": 3936,
        "lastPlayTime": 1603581978000,
        "championPointsSinceLastLevel": 2136,
        "championPointsUntilNextLevel": 2064,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 427,
        "championLevel": 2,
        "championPoints": 3597,
        "lastPlayTime": 1630541536000,
        "championPointsSinceLastLevel": 1797,
        "championPointsUntilNextLevel": 2403,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 20,
        "championLevel": 2,
        "championPoints": 3530,
        "lastPlayTime": 1617372274000,
        "championPointsSinceLastLevel": 1730,
        "championPointsUntilNextLevel": 2470,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 44,
        "championLevel": 2,
        "championPoints": 3179,
        "lastPlayTime": 1623432136000,
        "championPointsSinceLastLevel": 1379,
        "championPointsUntilNextLevel": 2821,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 56,
        "championLevel": 2,
        "championPoints": 3104,
        "lastPlayTime": 1626478926000,
        "championPointsSinceLastLevel": 1304,
        "championPointsUntilNextLevel": 2896,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 518,
        "championLevel": 2,
        "championPoints": 2785,
        "lastPlayTime": 1618596321000,
        "championPointsSinceLastLevel": 985,
        "championPointsUntilNextLevel": 3215,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 63,
        "championLevel": 2,
        "championPoints": 2649,
        "lastPlayTime": 1569636645000,
        "championPointsSinceLastLevel": 849,
        "championPointsUntilNextLevel": 3351,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 106,
        "championLevel": 2,
        "championPoints": 2534,
        "lastPlayTime": 1624150470000,
        "championPointsSinceLastLevel": 734,
        "championPointsUntilNextLevel": 3466,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 254,
        "championLevel": 2,
        "championPoints": 2389,
        "lastPlayTime": 1615081968000,
        "championPointsSinceLastLevel": 589,
        "championPointsUntilNextLevel": 3611,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 126,
        "championLevel": 2,
        "championPoints": 2232,
        "lastPlayTime": 1600821144000,
        "championPointsSinceLastLevel": 432,
        "championPointsUntilNextLevel": 3768,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 50,
        "championLevel": 2,
        "championPoints": 1868,
        "lastPlayTime": 1586565316000,
        "championPointsSinceLastLevel": 68,
        "championPointsUntilNextLevel": 4132,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 91,
        "championLevel": 1,
        "championPoints": 1485,
        "lastPlayTime": 1605380804000,
        "championPointsSinceLastLevel": 1485,
        "championPointsUntilNextLevel": 315,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 166,
        "championLevel": 1,
        "championPoints": 1444,
        "lastPlayTime": 1630705916000,
        "championPointsSinceLastLevel": 1444,
        "championPointsUntilNextLevel": 356,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 777,
        "championLevel": 1,
        "championPoints": 1283,
        "lastPlayTime": 1614717951000,
        "championPointsSinceLastLevel": 1283,
        "championPointsUntilNextLevel": 517,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 876,
        "championLevel": 1,
        "championPoints": 1223,
        "lastPlayTime": 1631910923000,
        "championPointsSinceLastLevel": 1223,
        "championPointsUntilNextLevel": 577,
        "chestGranted": true,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 113,
        "championLevel": 1,
        "championPoints": 1033,
        "lastPlayTime": 1630805315000,
        "championPointsSinceLastLevel": 1033,
        "championPointsUntilNextLevel": 767,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 83,
        "championLevel": 1,
        "championPoints": 954,
        "lastPlayTime": 1522534881000,
        "championPointsSinceLastLevel": 954,
        "championPointsUntilNextLevel": 846,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 90,
        "championLevel": 1,
        "championPoints": 940,
        "lastPlayTime": 1631408609000,
        "championPointsSinceLastLevel": 940,
        "championPointsUntilNextLevel": 860,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 25,
        "championLevel": 1,
        "championPoints": 900,
        "lastPlayTime": 1631051761000,
        "championPointsSinceLastLevel": 900,
        "championPointsUntilNextLevel": 900,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 420,
        "championLevel": 1,
        "championPoints": 883,
        "lastPlayTime": 1526169467000,
        "championPointsSinceLastLevel": 883,
        "championPointsUntilNextLevel": 917,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 164,
        "championLevel": 1,
        "championPoints": 416,
        "lastPlayTime": 1495955167000,
        "championPointsSinceLastLevel": 416,
        "championPointsUntilNextLevel": 1384,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 6,
        "championLevel": 1,
        "championPoints": 270,
        "lastPlayTime": 1600556927000,
        "championPointsSinceLastLevel": 270,
        "championPointsUntilNextLevel": 1530,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 240,
        "championLevel": 1,
        "championPoints": 150,
        "lastPlayTime": 1503280174000,
        "championPointsSinceLastLevel": 150,
        "championPointsUntilNextLevel": 1650,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    },
    {
        "championId": 526,
        "championLevel": 1,
        "championPoints": 122,
        "lastPlayTime": 1626480489000,
        "championPointsSinceLastLevel": 122,
        "championPointsUntilNextLevel": 1678,
        "chestGranted": false,
        "tokensEarned": 0,
        "summonerId": "EXHSBmagJiQTtYbshDxUGiHFIPWYydLAuIxbsGBmCqALYF8"
    }
]